escamboapp/config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site/home#index'

  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end

  namespace :backoffice do
    resources :admins, except: [:show]  
    resources :categories, except: [:show, :destroy]
    resources :send_mail, only: [:edit, :create]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]  
    end

    resources :ad_details, only: [:index, :show]
    resources :categories, only: [:show] 
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

escamboapp/app/views/layouts/backoffice_shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
<div class="navbar-header">
<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="index.html"><%= t('app.backoffice_subtitle') %></a>
</div>
<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right">

<li><%= current_admin.email %></li>

<!-- /.dropdown -->
<li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
    </a>
    <ul class="dropdown-menu dropdown-user">
        <li>
            <%= link_to destroy_admin_session_path, method: :delete do %>
                <i class="fa fa-sign-out fa-fw"></i>
                Sair
            <% end %>
        </li>
    </ul>
    <!-- /.dropdown-user -->
</li>
<!-- /.dropdown -->
</ul>
<!-- /.navbar-top-links -->

<div class="navbar-default sidebar" role="navigation">
<div class="sidebar-nav navbar-collapse">
    <ul class="nav" id="side-menu">
        <li>
            <%= link_to backoffice_path do %>
                <i class="fa fa-dashboard fa-fw"></i> <%= t('backoffice_menu.dashboard') %>
            <% end %>
        </li>
        <li>
            <%= link_to backoffice_categories_path do %>
                <i class="fa fa-th-list fa-fw"></i> <%= t('backoffice_menu.categories') %>
            <% end %>
        </li>
        <li>
            <%= link_to backoffice_admins_path do %>
                <i class="fa fa-users fa-fw"></i> <%= t('backoffice_menu.admins') %>
            <% end %>
        </li>

        <% if Rails.env.development? %>
            <li>
                <%= link_to backoffice_diagrams_path do %>
                    <i class="fa fa-database fa-fw"></i> <%= t('backoffice_menu.er_diagram') %>
                <% end %>
            </li>
        <% end %>
    </ul>
</div>
<!-- /.sidebar-collapse -->
</div>
<!-- /.navbar-static-side -->
</nav>