escamboapp/config/routes.rb
Rails.application.routes.draw do

  require "sidekiq/web"
  mount Sidekiq::Web => '/sidekiq'

  post '/rate' => 'rater#create', :as => 'rate'
  root 'site/home#index'

  get 'backoffice', to: 'backoffice/dashboard#index'
  
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end

  namespace :backoffice do
    resources :admins, except: [:show]  
    resources :categories, except: [:show, :destroy]
    resources :send_mail, only: [:edit, :create]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'

    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]  
    end

    resources :ad_details, only: [:index, :show]
    resources :categories, only: [:show] 
    resources :comments, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: { 
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

escamboapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('app.name') %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

escamboapp/app/views/layouts/backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.backoffice_subtitle') %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all' %>

    <%= javascript_include_tag 'charts' %>
    
    <%= csrf_meta_tags %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        <%= render partial: "layouts/backoffice_shared/navigation" %>

        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                    <!-- /.col-lg-12 -->
                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'backoffice' %>

    <%= render partial: 'layouts/shared/notifications'  %>
</body>

</html>

escamboapp/app/views/layouts/backoffice_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.backoffice_subtitle') %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'backoffice', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'backoffice' %>

    <%= csrf_meta_tags %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <%= yield %>
</body>

</html>

escamboapp/app/views/layouts/pdf.pdf.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.name') %></title>

    <%= wicked_pdf_stylesheet_link_tag    'application' %>
    <%= wicked_pdf_stylesheet_link_tag    'site' %>

    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="global-spin" class="loading" style="display: none;">Loading&#8230;</div>
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div id="home-detail" class="col-md-9">

                <div class="row">
                    <%= yield %>
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <%= wicked_pdf_javascript_include_tag 'application' %>
    <%= wicked_pdf_javascript_include_tag 'site' %>

</body>

</html>

escamboapp/app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.profile_subtitle') %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all' %>
    <%= stylesheet_link_tag    'site/profile', media: 'all' %>

    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <%= render partial: "layouts/site_shared/navigation" %>
    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <%= link_to "#{t('profile_menu.dashboard')}", site_profile_dashboard_index_path %>
                </li>
                <li>
                    <%= link_to "#{t('profile_menu.my_ads')}", site_profile_ads_path %>
                </li>
                <li>
                    <%= link_to "#{t('profile_menu.new_ad')}", new_site_profile_ad_path %>
                </li>
                <li>
                    <%= link_to "#{t('profile_menu.my_data')}", edit_site_profile_my_datum_path(current_member.id) %>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <%= yield %>
                    </div>
                </div>
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    <%= javascript_include_tag 'site/profile' %>
    <%#= javascript_include_tag 'site/profile/ads' %>

    <%= yield :javascripts %>

    <%= render partial: 'layouts/shared/notifications'  %>
</body>

</html>

escamboapp/app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.name') %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all' %>

    <%= csrf_meta_tags %>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <div id="global-spin" class="loading" style="display: none;">Loading&#8230;</div>
    <%= render partial: "layouts/site_shared/navigation" %>

    <!-- Page Content -->
    <div class="container">

        <%= form_tag site_search_path, method: :get do %>
            <div class="row">
                <div class="well well-sm">
                    <div class="row">
                      <div class="col-lg-3"></div>

                      <div class="col-lg-6">
                        <div class="input-group">

                          <%= text_field_tag(:q, params[:q] , { class:"form-control", placeholder: "#{cookies[:search_term] ? cookies[:search_term] : t('placeholder.search_for')}" }) %>

                          <span class="input-group-btn">
                            <%= submit_tag("#{t('buttons.search')}", class:"btn btn-default") %>
                          </span>
                        </div><!-- /input-group -->
                      </div><!-- /.col-lg-6 -->

                      <div class="col-lg-3"></div>
                    </div><!-- /.row -->
                </div>
            </div>
        <% end %>

        <div class="row">

            <%= render partial: 'layouts/site_shared/sidebar' %>

            <div id="home-detail" class="col-md-9">

                <% if controller_path == 'site/home' %>
                    <%= render partial: 'layouts/site_shared/carousel' %>
                <% end %>

                <div class="row">
                    <%= yield %>
                </div>

            </div>

        </div>

    </div>
    <!-- /.container -->

    <%= render partial: "layouts/site_shared/footer" %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>

    <%= render partial: 'layouts/shared/notifications'  %>
</body>

</html>

escamboapp/app/views/layouts/site_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t('app.site_subtitle') %></title>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= stylesheet_link_tag    'site', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>

    <%= csrf_meta_tags %>


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
    <%= yield %>
</body>

</html>